### http 공고 테스트 http 파일은 토큰이나 여타 정보가 있어서 작성하고 커밋 전에 워드에 저장해두면서 관리할게요~

### 특정 공고 조회
GET https://bootcamp-api.codeit.kr/api/11-2/the-julge/shops/de1fe478-2a82-48cb-8b21-bd019f5783c7/notices/ae893b96-2106-4fad-bce0-073bfd0042c7

### 특정 공고 지원
POST https://bootcamp-api.codeit.kr/api/11-2/the-julge/shops/6572e430-2689-4859-baa6-3be42a251648/notices/4cbd3f82-9da3-4ebb-a31c-a46052c46d7f/applications
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlYjA5ZTgyOS02MDYxLTQwMDgtYTRjZC1iMzc0NWU5ODhmMjkiLCJpYXQiOjE3MzUwNTI4NzN9.kXzNSMPekR6xyW6lH_H3iw7MBNxyk3z0nZq_g-TPqgU
Content-Type: application/json

{}


### 특정 공고 지원 조회
GET https://bootcamp-api.codeit.kr/api/11-2/the-julge/shops/6572e430-2689-4859-baa6-3be42a251648/notices/4cbd3f82-9da3-4ebb-a31c-a46052c46d7f/applications



### 회원가입
POST https://bootcamp-api.codeit.kr/api/11-2/the-julge/users
Content-Type: application/json

{
  "email": "test1123@test.com",
  "password": "test1123",
  "type": "employer"
}

### 로그인
POST https://bootcamp-api.codeit.kr/api/11-2/the-julge/token
Content-Type: application/json

{
  "email": "test1123@test.com",
  "password": "test1123"
}


### 가게 등록 
POST https://bootcamp-api.codeit.kr/api/11-2/the-julge/shops
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxMWIwN2ZlMy1iOTUxLTRhODEtOGMyNy0xMTg2MjAxMzlhNDYiLCJpYXQiOjE3MzUwNTMyNTh9.Sjf3WamOolt1-Aah6gU4N5TWw8sYadIVgt1-fm3-Mro

{
  "name": "버거최고맛집",
  "category": "양식",
  "address1": "서울시 은평구",
  "address2": "",
  "description": "요즈음 인기를 끄는 아메리칸 버거",
  "imageUrl": "https://bootcamp-project-api.s3.ap-northeast-2.amazonaws.com/11-2/the-julge/20f41d83-3e0b-42d0-a89f-b7eb83096f95-ex7.png",
  "originalHourlyPay": 13000
}


### 공고 등록
POST https://bootcamp-api.codeit.kr/api/11-2/the-julge/shops/6572e430-2689-4859-baa6-3be42a251648/notices
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxMWIwN2ZlMy1iOTUxLTRhODEtOGMyNy0xMTg2MjAxMzlhNDYiLCJpYXQiOjE3MzUwNTMyNTh9.Sjf3WamOolt1-Aah6gU4N5TWw8sYadIVgt1-fm3-Mro

{
  "hourlyPay": 20000,
  "startsAt": "2025-03-26T04:00:00Z",
  "workhour": 6,
  "description": "언제나 정성을 담아 버거를 만듭니다."
}

